### PR TITLE
updated and tested the template files with the latest Vault version

### PR DESCRIPTION
**Pull request by gautambaghel**
*Issue #, if available:*

*Description of changes:*
Updated to the latest version of Vault

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by wellsiau-aws — APPROVED** [review]
LGTM

**Review by gargana — APPROVED** [review]
LGTM

**Comment by gargana** [comment]
End to end tests not passing - have scheduled a new run

**Comment by gautambaghel** [comment]
> End to end tests not passing - have scheduled a new run

Hi @gargana! Anything I can do to help with this?

**Comment by gargana** [comment]
CI builds with some transient regional issues
```
[INFO   ] : ubuntu-base ap-south-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base eu-west-3 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base eu-west-2 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base eu-west-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base ap-northeast-2 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base ap-northeast-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base sa-east-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base ca-central-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base ap-southeast-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base ap-southeast-2 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base eu-central-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base us-east-1 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base us-east-2 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base us-west-2 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 ap-south-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 eu-west-3 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 eu-west-2 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 eu-west-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 ap-northeast-2 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 ap-northeast-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 sa-east-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 ca-central-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 ap-southeast-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 ap-southeast-2 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 eu-central-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 us-east-1 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 us-east-2 CREATE_IN_PROGRESS
[INFO   ] : cis-level-1 us-west-2 CREATE_IN_PROGRESS
[INFO   ] : ubuntu-base ca-central-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base us-east-2 CREATE_COMPLETE
[INFO   ] : cis-level-1 ca-central-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base eu-west-2 CREATE_COMPLETE
[INFO   ] : ubuntu-base us-east-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 eu-west-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 us-east-2 CREATE_COMPLETE
[INFO   ] : ubuntu-base eu-west-3 CREATE_COMPLETE
[INFO   ] : ubuntu-base sa-east-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base eu-central-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base ap-southeast-2 CREATE_COMPLETE
[INFO   ] : ubuntu-base eu-west-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base us-west-2 CREATE_COMPLETE
[INFO   ] : ubuntu-base ap-northeast-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 eu-west-2 CREATE_COMPLETE
[INFO   ] : cis-level-1 sa-east-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 eu-central-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base ap-south-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 ap-south-1 CREATE_COMPLETE
[INFO   ] : ubuntu-base ap-northeast-2 CREATE_COMPLETE
[INFO   ] : cis-level-1 eu-west-3 CREATE_COMPLETE
[INFO   ] : ubuntu-base ap-southeast-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 ap-southeast-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 ap-northeast-1 CREATE_COMPLETE
[INFO   ] : cis-level-1 ap-northeast-2 CREATE_COMPLETE
[INFO   ] : cis-level-1 ap-southeast-2 CREATE_COMPLETE
[ERROR  ] : cis-level-1 us-east-1 CREATE_FAILED
[ERROR  ] :     VaultServerAutoScalingGroup Received 2 SUCCESS signal(s) out of 3.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
[ERROR  ] : cis-level-1 us-west-2 CREATE_FAILED
[ERROR  ] :     VaultServerAutoScalingGroup Received 2 SUCCESS signal(s) out of 3.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

**Pull request merged**
